# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RelizKit' do
  use_frameworks!

  pod 'RZObservableKit'
  pod 'RZStoreKit'
  pod 'RZEvent'	
  pod 'RZDarkModeKit'
  pod 'RZViewBuilder'
  pod 'RZUIPacKit'

end
